DB_NAME = <YOUR_DB_NAME>
DB_HOST = <YOUR_DB_HOSTNAME>
DB_PORT = <YOUR_DB_PORT>
DB_USER = <YOUR_DB_USERNAME>
DB_PASS = <YOUR_DB_PASSWORD>
HOST = <YOUR_HOST_ADDRESS>
PORT = <YOUR_PORT>
FIREFOX_DRIVER = <PATH_TO_YOUR_GECKODRIVER>
